-- Verbesserungen:

--Datentypen analysieren und optimieren
-- Wechsel von DATE zu Minuten-Integer, Zwischen Puffer für Movie (New Duration=Old, delete Old)
ALTER TABLE "FHS52423"."MOVIES" MODIFY ("DURATION" NUMBER(4,0));
ALTER TABLE "FHS52423"."AUDIOS" MODIFY ("DURATION" NUMBER(4,0));

-- Optimierung der ISBN-Spalte von 50 auf 17
ALTER TABLE "FHS52423"."BOOKS" MODIFY ("ISBN_ID" VARCHAR2(17));

-- Erhöhung des Textpuffers für Medienbeschreibungen (Alternativ CLOB), same as movie
ALTER TABLE "FHS52423"."MEDIAS" MODIFY (
    "DESCRIPTION" CLOB) LOB ("DESCRIPTION") STORE AS MEDIAS_DESC_LOB (
    ENABLE STORAGE IN ROW
    CHUNK 8192
    RETENTION
    CACHE
);
-- Number größe enschränken, wenn Tabellen neu erstellt werden. (Wasn't used)
ALTER TABLE "FHS52423"."AUTHORS" MODIFY ("AUTHOR_ID" NUMBER(9,0));
ALTER TABLE "FHS52423"."CUSTOMERS" MODIFY ("CUSTOMER_ID" NUMBER(9,0));
ALTER TABLE "FHS52423"."GENRES" MODIFY ("GENRE_ID" NUMBER(4,0));
ALTER TABLE "FHS52423"."LOCATIONS" MODIFY ("LOC_ID" NUMBER(6,0));
ALTER TABLE "FHS52423"."MEDIA_TYPES" MODIFY ("TYPE_ID" NUMBER(3,0));
ALTER TABLE "FHS52423"."MEDIAS" MODIFY ("MEDIA_ID" NUMBER(9,0));

-- Theoretisch moeglich Barcode länge zu standardisieren => Char mit konst länge

--Storage-Optionen festlegen, gewählte Tabellen: Copies und Ledger
-- Für X-Medien bei kleineren Bücjhereien: 5.000 bis 15.000, größere: 35.000-100.000
-- https://www.bvoe.at/oeffentliche-bibliotheken/statistik-und-leistungsdaten
-- Physische Exemplare in ganz Salzburg: 923 635 => 100.000 für unsere Beispiel Bibliothek
-- Verleih in ganz Salzburg: 2 741 283=>274 128 

-- COPIES (100k Bestand, kaum Updates)
-- Zeilengröße: 12B (Barcode) + 5B (Media) + 4B (Comp) + 6B (Shelf) + 3B (Loc) + 3B (Header) = 33 Bytes
-- 100.000 Zeilen * 33 Bytes=3.300.000 Bytes =>4M Bytes
-- Next mit ca 10% neuer Medien 10.000*33B=330KB
ALTER TABLE "FHS52423"."COPIES" 
  PCTFREE 5
  --INITIAL 4M im laufenden betrieb nicht moeglich wenn gewünscht->drop table
  STORAGE ( NEXT 512K);

-- LEDGER (820k (Init Speicher für 3 Jahre), hohe Update-Frequenz)
-- Zeilengröße: 21B (3x Date) + 6B (2x Cost) + 22B (IDs & Barcode) + 3B (Header) = 52 Bytes
-- 822.384 Zeilen * 52 Bytes = 42.763.968 Bytes => 64M Bytes
-- Next mit ca 274.000 neuen Entlehnungen pro Jahr * 52 Bytes = 14,2MB => 10M Bytes
ALTER TABLE "FHS52423"."LEDGER" 
  PCTFREE 25
  --INITIAL 64M im laufenden betrieb nicht moeglich wenn gewünscht->drop table
  STORAGE (NEXT 16M);

--Add On (bei den Zwischentabellen, die nur IDS verbinden wird keine vergrößerung erwartet)
ALTER TABLE "FHS52423"."MEDIA_GENRE" PCTFREE 0;
ALTER TABLE "FHS52423"."WRITTEN_BY" PCTFREE 0;

--Zugriffspläne analysieren und optimieren


--DDL out of DBeaver
-- FHS52423.AUTHORS definition

CREATE TABLE "FHS52423"."AUTHORS" 
   (    "AUTHOR_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "LAST_NAME" VARCHAR2(50) NOT NULL ENABLE, 
    "FIRST_NAME" VARCHAR2(50), 
     CONSTRAINT "AUTHORS_PK" PRIMARY KEY ("AUTHOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "FHS52423"."TRG_AUTHORS_BI" 
BEFORE INSERT ON AUTHORS FOR EACH ROW
BEGIN
  IF :new.author_id IS NULL THEN
    SELECT AUTHOR_SEQ.NEXTVAL INTO :new.author_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "FHS52423"."TRG_AUTHORS_BI" ENABLE;

GRANT DELETE ON "FHS52423"."AUTHORS" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."AUTHORS" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."AUTHORS" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."AUTHORS" TO "FHS52415";


-- FHS52423.CUSTOMERS definition

CREATE TABLE "FHS52423"."CUSTOMERS" 
   (    "CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "CUSTOMER_FIRST_NAME" VARCHAR2(50), 
    "CUSTOMER_LAST_NAME" VARCHAR2(40) NOT NULL ENABLE, 
    "BIRTH_DATE" DATE NOT NULL ENABLE, 
     CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "FHS52423"."TRG_CUSTOMERS_BI" 
BEFORE INSERT ON CUSTOMERS FOR EACH ROW
BEGIN
  IF :new.customer_id IS NULL THEN
    SELECT CUSTOMER_SEQ.NEXTVAL INTO :new.customer_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "FHS52423"."TRG_CUSTOMERS_BI" ENABLE;

GRANT DELETE ON "FHS52423"."CUSTOMERS" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."CUSTOMERS" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."CUSTOMERS" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."CUSTOMERS" TO "FHS52415";


-- FHS52423.GENRES definition

CREATE TABLE "FHS52423"."GENRES" 
   (    "GENRE_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "CATEGORY" VARCHAR2(30) NOT NULL ENABLE, 
     CONSTRAINT "GENRES_PK" PRIMARY KEY ("GENRE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "FHS52423"."TRG_GENRES_BI" 
BEFORE INSERT ON GENRES FOR EACH ROW
BEGIN
  IF :new.genre_id IS NULL THEN
    SELECT GENRE_SEQ.NEXTVAL INTO :new.genre_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "FHS52423"."TRG_GENRES_BI" ENABLE;

GRANT DELETE ON "FHS52423"."GENRES" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."GENRES" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."GENRES" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."GENRES" TO "FHS52415";


-- FHS52423.LOCATIONS definition

CREATE TABLE "FHS52423"."LOCATIONS" 
   (    "LOC_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "NAME" VARCHAR2(30), 
    "STREET" VARCHAR2(50), 
     CONSTRAINT "LOCATIONS_PK" PRIMARY KEY ("LOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "FHS52423"."TRG_LOCATIONS_BI" 
BEFORE INSERT ON LOCATIONS FOR EACH ROW
BEGIN
  IF :new.loc_id IS NULL THEN
    SELECT LOCATION_SEQ.NEXTVAL INTO :new.loc_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "FHS52423"."TRG_LOCATIONS_BI" ENABLE;

GRANT DELETE ON "FHS52423"."LOCATIONS" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."LOCATIONS" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."LOCATIONS" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."LOCATIONS" TO "FHS52415";


-- FHS52423.MEDIA_TYPES definition

CREATE TABLE "FHS52423"."MEDIA_TYPES" 
   (    "TYPE_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "TYPE" VARCHAR2(30), 
     CONSTRAINT "MEDIA_TYPES_PK" PRIMARY KEY ("TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT DELETE ON "FHS52423"."MEDIA_TYPES" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."MEDIA_TYPES" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."MEDIA_TYPES" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."MEDIA_TYPES" TO "FHS52415";


-- FHS52423.MEDIAS definition

CREATE TABLE "FHS52423"."MEDIAS" 
   (    "MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "TITLE" VARCHAR2(50) NOT NULL ENABLE, 
    "DESCRIPTION" VARCHAR2(200) NOT NULL ENABLE, 
    "AGE_RESTRICTION" NUMBER(*,0) NOT NULL ENABLE, 
    "MEDIA_TYPES_TYPE_ID" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "MEDIAS_PK" PRIMARY KEY ("MEDIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."MEDIAS" ADD CONSTRAINT "MEDIAS_MEDIA_TYPES_FK" FOREIGN KEY ("MEDIA_TYPES_TYPE_ID")
      REFERENCES "FHS52423"."MEDIA_TYPES" ("TYPE_ID") ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "FHS52423"."TRG_MEDIAS_BI" 
BEFORE INSERT ON MEDIAS FOR EACH ROW
BEGIN
  IF :new.media_id IS NULL THEN
    SELECT MEDIA_SEQ.NEXTVAL INTO :new.media_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "FHS52423"."TRG_MEDIAS_BI" ENABLE;

GRANT DELETE ON "FHS52423"."MEDIAS" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."MEDIAS" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."MEDIAS" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."MEDIAS" TO "FHS52415";


-- FHS52423.MEDIA_GENRE definition

CREATE TABLE "FHS52423"."MEDIA_GENRE" 
   (    "GENRES_GENRE_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "MEDIAS_MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "MEDIA_GENRE_PK" PRIMARY KEY ("GENRES_GENRE_ID", "MEDIAS_MEDIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."MEDIA_GENRE" ADD CONSTRAINT "MEDIA_GENRE_GENRES_FK" FOREIGN KEY ("GENRES_GENRE_ID")
      REFERENCES "FHS52423"."GENRES" ("GENRE_ID") ENABLE;
  ALTER TABLE "FHS52423"."MEDIA_GENRE" ADD CONSTRAINT "MEDIA_GENRE_MEDIAS_FK" FOREIGN KEY ("MEDIAS_MEDIA_ID")
      REFERENCES "FHS52423"."MEDIAS" ("MEDIA_ID") ENABLE;

GRANT DELETE ON "FHS52423"."MEDIA_GENRE" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."MEDIA_GENRE" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."MEDIA_GENRE" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."MEDIA_GENRE" TO "FHS52415";


-- FHS52423.MOVIES definition

CREATE TABLE "FHS52423"."MOVIES" 
   (    "MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "FORMAT" VARCHAR2(20) NOT NULL ENABLE, 
    "DURATION" DATE NOT NULL ENABLE, 
     CONSTRAINT "MOVIES_PK" PRIMARY KEY ("MEDIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."MOVIES" ADD CONSTRAINT "MOVIES_MEDIAS_FK" FOREIGN KEY ("MEDIA_ID")
      REFERENCES "FHS52423"."MEDIAS" ("MEDIA_ID") ENABLE;

GRANT DELETE ON "FHS52423"."MOVIES" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."MOVIES" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."MOVIES" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."MOVIES" TO "FHS52415";


-- FHS52423.PRICES definition

CREATE TABLE "FHS52423"."PRICES" 
   (    "MEDIA_TYPES_TYPE_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "GENRES_GENRE_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "CREATION_DATE" DATE NOT NULL ENABLE, 
    "COST" NUMBER(9,2), 
    "VALID" DATE, 
     CONSTRAINT "PRICES_PK" PRIMARY KEY ("MEDIA_TYPES_TYPE_ID", "GENRES_GENRE_ID", "CREATION_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."PRICES" ADD CONSTRAINT "PRICES_GENRES_FK" FOREIGN KEY ("GENRES_GENRE_ID")
      REFERENCES "FHS52423"."GENRES" ("GENRE_ID") ENABLE;
  ALTER TABLE "FHS52423"."PRICES" ADD CONSTRAINT "PRICES_MEDIA_TYPES_FK" FOREIGN KEY ("MEDIA_TYPES_TYPE_ID")
      REFERENCES "FHS52423"."MEDIA_TYPES" ("TYPE_ID") ENABLE;

GRANT DELETE ON "FHS52423"."PRICES" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."PRICES" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."PRICES" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."PRICES" TO "FHS52415";


-- FHS52423.RESERVATIONS definition

CREATE TABLE "FHS52423"."RESERVATIONS" 
   (    "RESERVATION_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "TIME_RESERVATION" DATE NOT NULL ENABLE, 
    "CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "STATUS" VARCHAR2(20), 
    "BARCODE_ID" VARCHAR2(15), 
    "START_DATE" DATE, 
     CONSTRAINT "RESERVATIONS_PK" PRIMARY KEY ("RESERVATION_ID", "MEDIA_ID", "CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."RESERVATIONS" ADD CONSTRAINT "RESERVATIONS_CUSTOMERS_FK" FOREIGN KEY ("CUSTOMER_ID")
      REFERENCES "FHS52423"."CUSTOMERS" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "FHS52423"."RESERVATIONS" ADD CONSTRAINT "RESERVATIONS_MEDIAS_FK" FOREIGN KEY ("MEDIA_ID")
      REFERENCES "FHS52423"."MEDIAS" ("MEDIA_ID") ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "FHS52423"."TRG_RESERVATIONS_BI" 
BEFORE INSERT ON RESERVATIONS FOR EACH ROW
BEGIN
  IF :new.reservation_id IS NULL THEN
    SELECT RESERVATION_SEQ.NEXTVAL INTO :new.reservation_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "FHS52423"."TRG_RESERVATIONS_BI" ENABLE;

GRANT DELETE ON "FHS52423"."RESERVATIONS" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."RESERVATIONS" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."RESERVATIONS" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."RESERVATIONS" TO "FHS52415";


-- FHS52423.SHELVES definition

CREATE TABLE "FHS52423"."SHELVES" 
   (    "SHELF_ID" VARCHAR2(10) NOT NULL ENABLE, 
    "LOCATIONS_LOC_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "SHELF_CODE" VARCHAR2(20), 
     CONSTRAINT "SHELVES_PK" PRIMARY KEY ("SHELF_ID", "LOCATIONS_LOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."SHELVES" ADD CONSTRAINT "SHELVES_LOCATIONS_FK" FOREIGN KEY ("LOCATIONS_LOC_ID")
      REFERENCES "FHS52423"."LOCATIONS" ("LOC_ID") ENABLE;

GRANT DELETE ON "FHS52423"."SHELVES" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."SHELVES" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."SHELVES" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."SHELVES" TO "FHS52415";


-- FHS52423.AUDIOS definition

CREATE TABLE "FHS52423"."AUDIOS" 
   (    "MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "CODEC" VARCHAR2(20) NOT NULL ENABLE, 
    "DURATION" DATE NOT NULL ENABLE, 
     CONSTRAINT "AUDIOS_PK" PRIMARY KEY ("MEDIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."AUDIOS" ADD CONSTRAINT "AUDIOS_MEDIAS_FK" FOREIGN KEY ("MEDIA_ID")
      REFERENCES "FHS52423"."MEDIAS" ("MEDIA_ID") ENABLE;

GRANT DELETE ON "FHS52423"."AUDIOS" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."AUDIOS" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."AUDIOS" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."AUDIOS" TO "FHS52415";


-- FHS52423.BOOKS definition

CREATE TABLE "FHS52423"."BOOKS" 
   (    "MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "ISBN_ID" VARCHAR2(50) NOT NULL ENABLE, 
     CONSTRAINT "BOOKS_PK" PRIMARY KEY ("MEDIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."BOOKS" ADD CONSTRAINT "BOOKS_MEDIAS_FK" FOREIGN KEY ("MEDIA_ID")
      REFERENCES "FHS52423"."MEDIAS" ("MEDIA_ID") ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "FHS52423"."ARC_FKARC_3_BOOKS" 
BEFORE INSERT OR UPDATE OF media_id ON BOOKS 
FOR EACH ROW 
DECLARE 
    d INTEGER; 
BEGIN 
    SELECT A.MEDIA_TYPES_type_id INTO d FROM MEDIAS A WHERE A.media_id = :new.media_id; 
    -- Hier sollte '1' (oder die entsprechende ID für Books) stehen
    IF (d IS NULL) THEN 
        raise_application_error(-20223,'FK BOOKS_MEDIAS_FK violates Arc constraint.'); 
    END IF; 
EXCEPTION WHEN NO_DATA_FOUND THEN NULL; 
END; 
/
ALTER TRIGGER "FHS52423"."ARC_FKARC_3_BOOKS" ENABLE;

GRANT DELETE ON "FHS52423"."BOOKS" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."BOOKS" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."BOOKS" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."BOOKS" TO "FHS52415";


-- FHS52423.COMPARTMENTS definition

CREATE TABLE "FHS52423"."COMPARTMENTS" 
   (    "COMP_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "SHELVES_SHELF_ID" VARCHAR2(10) NOT NULL ENABLE, 
    "SHELVES_LOCATIONS_LOC_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "POSITION" VARCHAR2(20), 
     CONSTRAINT "COMPARTMENTS_PK" PRIMARY KEY ("COMP_ID", "SHELVES_SHELF_ID", "SHELVES_LOCATIONS_LOC_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."COMPARTMENTS" ADD CONSTRAINT "COMPARTMENTS_SHELVES_FK" FOREIGN KEY ("SHELVES_SHELF_ID", "SHELVES_LOCATIONS_LOC_ID")
      REFERENCES "FHS52423"."SHELVES" ("SHELF_ID", "LOCATIONS_LOC_ID") ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "FHS52423"."TRG_COMPARTMENTS_BI" 
BEFORE INSERT ON COMPARTMENTS FOR EACH ROW
BEGIN
  IF :new.comp_id IS NULL THEN
    SELECT COMPARTMENT_SEQ.NEXTVAL INTO :new.comp_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "FHS52423"."TRG_COMPARTMENTS_BI" ENABLE;

GRANT DELETE ON "FHS52423"."COMPARTMENTS" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."COMPARTMENTS" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."COMPARTMENTS" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."COMPARTMENTS" TO "FHS52415";


-- FHS52423.COPIES definition

CREATE TABLE "FHS52423"."COPIES" 
   (    "BARCODE_ID" VARCHAR2(15) NOT NULL ENABLE, 
    "MEDIAS_MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "COMPARTMENTS_COMP_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "COMPARTMENTS_SHELF_ID" VARCHAR2(10) NOT NULL ENABLE, 
    "COMPARTMENTS_LOC_ID" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "COPIES_PK" PRIMARY KEY ("BARCODE_ID", "MEDIAS_MEDIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."COPIES" ADD CONSTRAINT "COPIES_MEDIAS_FK" FOREIGN KEY ("MEDIAS_MEDIA_ID")
      REFERENCES "FHS52423"."MEDIAS" ("MEDIA_ID") ENABLE;
  ALTER TABLE "FHS52423"."COPIES" ADD CONSTRAINT "COPIES_COMPARTMENTS_FK" FOREIGN KEY ("COMPARTMENTS_COMP_ID", "COMPARTMENTS_SHELF_ID", "COMPARTMENTS_LOC_ID")
      REFERENCES "FHS52423"."COMPARTMENTS" ("COMP_ID", "SHELVES_SHELF_ID", "SHELVES_LOCATIONS_LOC_ID") ENABLE;

GRANT DELETE ON "FHS52423"."COPIES" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."COPIES" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."COPIES" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."COPIES" TO "FHS52415";


-- FHS52423.LEDGER definition

CREATE TABLE "FHS52423"."LEDGER" 
   (    "START_DATE" DATE NOT NULL ENABLE, 
    "END_DATE" DATE NOT NULL ENABLE, 
    "RETURN_DTIME" DATE, 
    "TOTAL_COST" NUMBER(9,2), 
    "COST_PAID" NUMBER(9,2), 
    "CUSTOMERS_CUSTOMER_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "COPIES_BARCODE_ID" VARCHAR2(15) NOT NULL ENABLE, 
    "COPIES_MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "LEDGER_PK" PRIMARY KEY ("CUSTOMERS_CUSTOMER_ID", "COPIES_BARCODE_ID", "COPIES_MEDIA_ID", "START_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."LEDGER" ADD CONSTRAINT "LEDGER_CUSTOMERS_FK" FOREIGN KEY ("CUSTOMERS_CUSTOMER_ID")
      REFERENCES "FHS52423"."CUSTOMERS" ("CUSTOMER_ID") ENABLE;
  ALTER TABLE "FHS52423"."LEDGER" ADD CONSTRAINT "LEDGER_COPIES_FK" FOREIGN KEY ("COPIES_BARCODE_ID", "COPIES_MEDIA_ID")
      REFERENCES "FHS52423"."COPIES" ("BARCODE_ID", "MEDIAS_MEDIA_ID") ENABLE;

GRANT DELETE ON "FHS52423"."LEDGER" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."LEDGER" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."LEDGER" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."LEDGER" TO "FHS52415";


-- FHS52423.MAGAZINES definition

CREATE TABLE "FHS52423"."MAGAZINES" 
   (    "MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "EDITION" VARCHAR2(30), 
     CONSTRAINT "MAGAZINES_PK" PRIMARY KEY ("MEDIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."MAGAZINES" ADD CONSTRAINT "MAGAZINES_MEDIAS_FK" FOREIGN KEY ("MEDIA_ID")
      REFERENCES "FHS52423"."MEDIAS" ("MEDIA_ID") ENABLE;

GRANT DELETE ON "FHS52423"."MAGAZINES" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."MAGAZINES" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."MAGAZINES" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."MAGAZINES" TO "FHS52415";


-- FHS52423."STATISTICS" definition

CREATE TABLE "FHS52423"."STATISTICS" 
   (    "STATISTIC_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "NUMBER_TIME_BORROWED" NUMBER(*,0), 
    "SUM_TIME_BORROWED" NUMBER(*,0), 
    "COPIES_BARCODE_ID" VARCHAR2(15) NOT NULL ENABLE, 
    "COPIES_MEDIAS_MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "STATISTICS_PK" PRIMARY KEY ("STATISTIC_ID", "COPIES_BARCODE_ID", "COPIES_MEDIAS_MEDIA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."STATISTICS" ADD CONSTRAINT "STATISTICS_COPIES_FK" FOREIGN KEY ("COPIES_BARCODE_ID", "COPIES_MEDIAS_MEDIA_ID")
      REFERENCES "FHS52423"."COPIES" ("BARCODE_ID", "MEDIAS_MEDIA_ID") ENABLE;

CREATE OR REPLACE NONEDITIONABLE TRIGGER "FHS52423"."TRG_STATISTICS_BI" 
BEFORE INSERT ON STATISTICS FOR EACH ROW
BEGIN
  IF :new.statistic_id IS NULL THEN
    SELECT STATISTIC_SEQ.NEXTVAL INTO :new.statistic_id FROM dual;
  END IF;
END;
/
ALTER TRIGGER "FHS52423"."TRG_STATISTICS_BI" ENABLE;

CREATE UNIQUE INDEX "FHS52423"."STATISTICS__IDX" ON "FHS52423"."STATISTICS" ("COPIES_BARCODE_ID", "COPIES_MEDIAS_MEDIA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

GRANT DELETE ON "FHS52423"."STATISTICS" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."STATISTICS" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."STATISTICS" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."STATISTICS" TO "FHS52415";


-- FHS52423.WRITTEN_BY definition

CREATE TABLE "FHS52423"."WRITTEN_BY" 
   (    "BOOKS_MEDIA_ID" NUMBER(*,0) NOT NULL ENABLE, 
    "AUTHORS_AUTHOR_ID" NUMBER(*,0) NOT NULL ENABLE, 
     CONSTRAINT "WRITTEN_BY_PK" PRIMARY KEY ("BOOKS_MEDIA_ID", "AUTHORS_AUTHOR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

ALTER TABLE "FHS52423"."WRITTEN_BY" ADD CONSTRAINT "WRITTEN_BY_BOOKS_FK" FOREIGN KEY ("BOOKS_MEDIA_ID")
      REFERENCES "FHS52423"."BOOKS" ("MEDIA_ID") ENABLE;
  ALTER TABLE "FHS52423"."WRITTEN_BY" ADD CONSTRAINT "WRITTEN_BY_AUTHORS_FK" FOREIGN KEY ("AUTHORS_AUTHOR_ID")
      REFERENCES "FHS52423"."AUTHORS" ("AUTHOR_ID") ENABLE;

GRANT DELETE ON "FHS52423"."WRITTEN_BY" TO "FHS52415";
  GRANT INSERT ON "FHS52423"."WRITTEN_BY" TO "FHS52415";
  GRANT SELECT ON "FHS52423"."WRITTEN_BY" TO "FHS52415";
  GRANT UPDATE ON "FHS52423"."WRITTEN_BY" TO "FHS52415";
