--CUSTOMER



SELECT * FROM CUSTOMER;

UPDATE CUSTOMER c SET birth_date = TO_DATE('01.01.1900','DD.MM.YYYY')
WHERE first_name = 'Alexander';

INSERT INTO CUSTOMER (first_name, last_name, birth_date) VALUES ('Alexander','Lux',TO_DATE('01.01.1900','DD.MM.YYYY'));
INSERT INTO CUSTOMER (first_name, last_name, birth_date) VALUES ('Susanne','Lastowicka',TO_DATE('02.02.1902','DD.MM.YYYY'));

INSERT INTO CUSTOMER (first_name, last_name, birth_date) VALUES ('Max','Mustermann',TO_DATE('02.02.2002','DD.MM.YYYY'));


-- MEDIA TYPE

INSERT INTO FHS52423.MEDIA_TYPE
(MEDIA_TYPE_ID, NAME)
VALUES(0, 'BOOK');

INSERT INTO FHS52423.MEDIA_TYPE
(MEDIA_TYPE_ID, NAME)
VALUES(1, 'MOVIE');

INSERT INTO FHS52423.MEDIA_TYPE
(MEDIA_TYPE_ID, NAME)
VALUES(2, 'AUDIO');

INSERT INTO FHS52423.MEDIA_TYPE
(MEDIA_TYPE_ID, NAME)
VALUES(3, 'MAGAZINE');

SELECT * FROM FHS52423.MEDIA_TYPE mt
ORDER BY MEDIA_TYPE_ID;


--MEDIA
INSERT INTO FHS52423.MEDIA
(TITLE, DESCRIPTION, AGE_RESTRICTION, MEDIA_TYPE_ID)
VALUES('Star Wars Episode I', 'A long time ago in a galaxy far, far away', 6, 1);

INSERT INTO FHS52423.MEDIA
( TITLE, DESCRIPTION, AGE_RESTRICTION, MEDIA_TYPE_ID)
VALUES( '1984', '1984, geschrieben von 1946 bis 1948 ', 16, 0);

INSERT INTO FHS52423.MEDIA
( TITLE, DESCRIPTION, AGE_RESTRICTION, MEDIA_TYPE_ID)
VALUES( 'Hiraeth', 'homesickness', 0, 2);

INSERT INTO FHS52423.MEDIA
( TITLE, DESCRIPTION, AGE_RESTRICTION, MEDIA_TYPE_ID)
VALUES( 'Vogue', 'Druckerzeugnis', 0, 3);

-- ID erhöht auf 7 durch ausführen aber blockierung durch konstrient, dass es einen passenden MEDIA_TYPE gibt.
INSERT INTO FHS52423.MEDIA
( TITLE, DESCRIPTION, AGE_RESTRICTION, MEDIA_TYPE_ID)
VALUES( 'TEST', 'test', 18, 0);

SELECT * FROM MEDIA;



-- CONCRETE MEDIA TYPE (BOOK; MOVIE; AUDIO; MAGAZINE)
--BOOK
INSERT INTO FHS52423.BOOKS (MEDIA_ID, ISBN)
VALUES (
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = '1984'), 
    '9-9-9-9'
);
--MOVIE
INSERT INTO FHS52423.MOVIES (MEDIA_ID, FORMAT, DURATION)
VALUES (
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = 'Star Wars Episode I'), 
    '35mm',136 
);
--AUDIO
INSERT INTO FHS52423.AUDIO (MEDIA_ID, CODEC, DURATION)
VALUES (
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = 'Hiraeth'), 
    'mp3',3.2
);
--MAGAZINE
INSERT INTO FHS52423.MAGAZINES (MEDIA_ID, EDITION)
VALUES (
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = 'Vogue'), 
    1
);

--Select all Media (AI)

SELECT 
    m.TITLE,
    m.DESCRIPTION,
    b.ISBN,           -- Details aus BOOKS
    mo.FORMAT,        -- Details aus MOVIES
    mo.DURATION AS MOVIE_MIN, 
    a.CODEC,          -- Details aus AUDIO
    a.DURATION AS AUDIO_MIN,
    ma.EDITION        -- Details aus MAGAZINES
FROM FHS52423.MEDIA m
LEFT JOIN FHS52423.BOOKS b     ON m.MEDIA_ID = b.MEDIA_ID
LEFT JOIN FHS52423.MOVIES mo   ON m.MEDIA_ID = mo.MEDIA_ID
LEFT JOIN FHS52423.AUDIO a     ON m.MEDIA_ID = a.MEDIA_ID
LEFT JOIN FHS52423.MAGAZINES ma ON m.MEDIA_ID = ma.MEDIA_ID;



--AUTHOR

INSERT INTO FHS52423.AUTHORS
( FIRST_NAME, LAST_NAME)
VALUES('Sapphṓ', 'Ψάπφω');

INSERT INTO FHS52423.AUTHORS
( FIRST_NAME, LAST_NAME)
VALUES('George', 'Orwell');

SELECT * FROM AUTHORS;

--AUTHOREN DIE ETWAS GESCHRIEBEN HABEN UND DEREN MEDIEN
--WRITTEN_BY

INSERT INTO FHS52423.WRITTEN_BY (AUTHOR_ID, MEDIA_ID)
VALUES (
    (SELECT AUTHOR_ID FROM FHS52423.AUTHORS WHERE LAST_NAME = 'Orwell' AND FIRST_NAME = 'George'),
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = '1984')
);

SELECT *
FROM FHS52423.MEDIA M
INNER JOIN FHS52423.WRITTEN_BY WB ON M.MEDIA_ID = WB.MEDIA_ID
INNER JOIN FHS52423.AUTHORS A    ON WB.AUTHOR_ID = A.AUTHOR_ID; 

--GENRE

INSERT INTO FHS52423.GENRE
(NAME)
VALUES('SCI-FI');

INSERT INTO FHS52423.GENRE
(NAME)
VALUES('Romance');

INSERT INTO FHS52423.GENRE
(NAME)
VALUES('Dystopie');

INSERT INTO FHS52423.GENRE
(NAME)
VALUES('Mode- und Lifestyle');

--VERBINDE MEDIA und GENRE

-- Star Wars SCI-FI
INSERT INTO FHS52423.MEDIA_GENRE (MEDIA_ID, GENRE_ID)
VALUES (
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = 'Star Wars Episode I'),
    (SELECT GENRE_ID FROM FHS52423.GENRE WHERE NAME = 'SCI-FI')
);

-- 1984  Dystopie
INSERT INTO FHS52423.MEDIA_GENRE (MEDIA_ID, GENRE_ID)
VALUES (
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = '1984'),
    (SELECT GENRE_ID FROM FHS52423.GENRE WHERE NAME = 'Dystopie')
);

-- Hiraeth  Romance
INSERT INTO FHS52423.MEDIA_GENRE (MEDIA_ID, GENRE_ID)
VALUES (
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = 'Hiraeth'),
    (SELECT GENRE_ID FROM FHS52423.GENRE WHERE NAME = 'Romance')
);
INSERT INTO FHS52423.MEDIA_GENRE (MEDIA_ID, GENRE_ID)
VALUES (
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = 'Hiraeth'),
    (SELECT GENRE_ID FROM FHS52423.GENRE WHERE NAME = 'Dystopie')
);

-- Vogue  Mode- und Lifestyle
INSERT INTO FHS52423.MEDIA_GENRE (MEDIA_ID, GENRE_ID)
VALUES (
    (SELECT MEDIA_ID FROM FHS52423.MEDIA WHERE TITLE = 'Vogue'),
    (SELECT GENRE_ID FROM FHS52423.GENRE WHERE NAME = 'Mode- und Lifestyle')
);

SELECT m.TITLE, g.NAME AS GENRE
FROM FHS52423.MEDIA m
JOIN FHS52423.MEDIA_GENRE mg ON m.MEDIA_ID = mg.MEDIA_ID
JOIN FHS52423.GENRE g       ON mg.GENRE_ID = g.GENRE_ID
ORDER BY m.TITLE;


-- LOCATION
INSERT INTO FHS52423.LOCATION
( NAME, STREET)
VALUES('Stadtbibliothek Bischofshofen', 'Kinostraße 4');

INSERT INTO FHS52423.LOCATION
( NAME, STREET)
VALUES('Stadtbücherei Hallein', 'Schöndorferpl. 6');

SELECT * FROM LOCATION l;
--shelves
--BISCHOFSHOFEN
INSERT INTO FHS52423.SHELVES
( LOCATION_ID, SHELF_CODE)
VALUES( 1, 'REGAL A1');

INSERT INTO FHS52423.SHELVES
( LOCATION_ID, SHELF_CODE)
VALUES( 1, 'REGAL B2');
--HALLEIN
INSERT INTO FHS52423.SHELVES
( LOCATION_ID, SHELF_CODE)
VALUES( 2, 'REGAL A1');

INSERT INTO FHS52423.SHELVES
( LOCATION_ID, SHELF_CODE)
VALUES( 2, 'REGAL B1');


SELECT s.SHELF_ID,l.NAME,s.SHELF_CODE  FROM SHELVES s INNER JOIN LOCATION l ON s.LOCATION_ID = l.LOCATION_ID;

-- COMPARTMENT

INSERT INTO FHS52423.COMPARTMENT
( SHELF_ID, "POSITION")
VALUES( 1, 'Oben');
INSERT INTO FHS52423.COMPARTMENT
( SHELF_ID, "POSITION")
VALUES( 1, 'Mitte');
INSERT INTO FHS52423.COMPARTMENT
( SHELF_ID, "POSITION")
VALUES( 1, 'Unten');

INSERT INTO FHS52423.COMPARTMENT
( SHELF_ID, "POSITION")
VALUES( 2, 'Oben');
INSERT INTO FHS52423.COMPARTMENT
( SHELF_ID, "POSITION")
VALUES( 2, 'Unten');

INSERT INTO FHS52423.COMPARTMENT
( SHELF_ID, "POSITION")
VALUES( 3, 'Oben');
INSERT INTO FHS52423.COMPARTMENT
( SHELF_ID, "POSITION")
VALUES( 4, 'Unten');

SELECT * FROM COMPARTMENT c
ORDER BY c.SHELF_ID;

--COPIES

INSERT INTO FHS52423.COPY (barcode, media_id, compartment_id)
VALUES (
    'BC001',
    (SELECT media_id FROM MEDIA WHERE title = 'Hiraeth'),
    2
);

INSERT INTO FHS52423.COPY (barcode, media_id, compartment_id)
VALUES (
    'BC002',
    (SELECT media_id FROM MEDIA WHERE title = 'Star Wars Episode I'),
    2
);

INSERT INTO FHS52423.COPY (barcode, media_id, compartment_id)
VALUES (
    'BC003',
    (SELECT media_id FROM MEDIA WHERE title = '1984'),
    1
);


INSERT INTO FHS52423.COPY (barcode, media_id, compartment_id)
VALUES (
    'BC004',
    (SELECT media_id FROM MEDIA WHERE title = 'Star Wars Episode I'),
    4
);

SELECT * FROM COPY;

--COST_EVAL

-- BOOK
INSERT INTO FHS52423.COST_EVALUATION
(MEDIA_TYPE_ID, COST, VALID, CREATION_DATE, GENRE_ID)
VALUES(0, 1.5, 'Y', SYSDATE, 1);

-- MOVIE
INSERT INTO FHS52423.COST_EVALUATION
(MEDIA_TYPE_ID, COST, VALID, CREATION_DATE, GENRE_ID)
VALUES(1, 3, 'Y', SYSDATE, 2);

-- AUDIO
INSERT INTO FHS52423.COST_EVALUATION
(MEDIA_TYPE_ID, COST, VALID, CREATION_DATE, GENRE_ID)
VALUES(2, 2, 'Y', SYSDATE, 3);

INSERT INTO FHS52423.COST_EVALUATION
(MEDIA_TYPE_ID, COST, VALID, CREATION_DATE, GENRE_ID)
VALUES(2, 10, 'Y', SYSDATE, 2);

-- MAGAZINE
INSERT INTO FHS52423.COST_EVALUATION
(MEDIA_TYPE_ID, COST, VALID, CREATION_DATE, GENRE_ID)
VALUES(3, 1, 'Y', SYSDATE, 4);


SELECT * FROM FHS52423.COST_EVALUATION;

--LEDGER
INSERT INTO FHS52423.LEDGER
(CUSTOMER_ID, COPY_ID, START_DATE, END_DATE, TOTAL_COST, MEDIA_TYPE_ID, GENRE_ID)
VALUES (
    (SELECT customer_id FROM CUSTOMER WHERE last_name = 'Lux'),
    (SELECT copy_id FROM COPY WHERE barcode = 'BC004'),
    SYSDATE - 10,
    SYSDATE - 5,
    (SELECT MAX(COST) FROM COST_EVALUATION WHERE media_type_id = 0),
    0,
    (SELECT genre_id FROM COST_EVALUATION 
     WHERE media_type_id = 0 AND cost = (SELECT MAX(cost) FROM COST_EVALUATION WHERE media_type_id = 0)
     AND ROWNUM = 1) 
);

INSERT INTO FHS52423.LEDGER
(CUSTOMER_ID, COPY_ID, START_DATE, END_DATE, TOTAL_COST, MEDIA_TYPE_ID, GENRE_ID)
VALUES (
    (SELECT customer_id FROM CUSTOMER WHERE last_name = 'Zach'),
    (SELECT copy_id FROM COPY WHERE barcode = 'BC001'),
    SYSDATE - 9,
    SYSDATE - 5,
    (SELECT MAX(COST) FROM COST_EVALUATION WHERE media_type_id = 2),
    2,
    (SELECT genre_id FROM COST_EVALUATION 
     WHERE media_type_id = 2 AND cost = (SELECT MAX(cost) FROM COST_EVALUATION WHERE media_type_id = 2)
     AND ROWNUM = 1) 
);

UPDATE FHS52423.LEDGER l
SET l.TOTAL_COST = (
    SELECT MAX(ce.COST) 
    FROM FHS52423.COST_EVALUATION ce 
    WHERE ce.MEDIA_TYPE_ID = l.MEDIA_TYPE_ID
)
WHERE l.TOTAL_COST IS NULL;

SELECT * FROM LEDGER l;

-- AI LEDGER JOIN
SELECT 
    l.LEDGER_ID AS ID,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS KUNDE,
    m.TITLE AS MEDIUM_TITEL,
    cp.BARCODE,
    mt.NAME AS TYP,
    g.NAME AS GENRE,
    TO_CHAR(l.START_DATE, 'DD.MM.YYYY') AS AUSGELIEHEN,
    TO_CHAR(l.END_DATE, 'DD.MM.YYYY') AS RUECKGABE_SOLL,
    l.TOTAL_COST || ' €' AS PREIS
FROM FHS52423.LEDGER l
JOIN FHS52423.CUSTOMER c       ON l.CUSTOMER_ID = c.CUSTOMER_ID
JOIN FHS52423.COPY cp           ON l.COPY_ID = cp.COPY_ID
JOIN FHS52423.MEDIA m           ON cp.MEDIA_ID = m.MEDIA_ID
JOIN FHS52423.MEDIA_TYPE mt     ON m.MEDIA_TYPE_ID = mt.MEDIA_TYPE_ID
JOIN FHS52423.GENRE g           ON l.GENRE_ID = g.GENRE_ID
-- Optional: Falls du nur Einträge willst, die auch in der Preis-Matrix sind
JOIN FHS52423.COST_EVALUATION ce ON (l.GENRE_ID = ce.GENRE_ID AND l.MEDIA_TYPE_ID = ce.MEDIA_TYPE_ID)
ORDER BY l.START_DATE DESC;

--RESERVIERUNG

INSERT INTO FHS52423.RESERVATION (
    customer_id,
    copy_id,
    reservation_date,
    status
)
VALUES (
    (SELECT customer_id FROM CUSTOMER WHERE last_name = 'Lastowicka'),
    (SELECT copy_id FROM COPY WHERE barcode = 'BC004'),
    SYSDATE,
    'AKTIV'
);

INSERT INTO FHS52423.RESERVATIONS 
(TIME_RESERVATION, CUSTOMER_ID, MEDIA_ID, STATUS)
VALUES (
    SYSDATE, 
    (SELECT customer_id FROM CUSTOMERS WHERE CUSTOMER_LAST_NAME = 'Lux' AND ROWNUM = 1), 
    (SELECT media_id FROM MEDIAS WHERE TITLE = 'The Hobbit' AND ROWNUM = 1), 
    'PENDING'
);

SELECT * FROM RESERVATION r;

--STATISTIC

INSERT INTO FHS52423.STATISTIC
(COPY_ID, NUMBER_TIME_BORROWED, SUM_TIME_BORROWED)
VALUES((SELECT copy_id FROM COPY WHERE barcode = 'BC004'), 1, 0);

INSERT INTO FHS52423.STATISTIC
(COPY_ID, NUMBER_TIME_BORROWED, SUM_TIME_BORROWED)
VALUES((SELECT copy_id FROM COPY WHERE barcode = 'BC002'), 1, 0);


SELECT * FROM BOOKS;
SELECT * FROM MEDIA;







