-- DROP OLD SCHEMA

-- Triggers
DROP TRIGGER ARC_FKArc_2_MAGAZINES;
DROP TRIGGER ARC_FKArc_2_BOOKS;
DROP TRIGGER ARC_FKArc_2_MOVIES;
DROP TRIGGER ARC_FKArc_2_AUDIOS;

-- M:N tables
DROP TABLE written_by CASCADE CONSTRAINTS;
DROP TABLE MEDIA_GENRE CASCADE CONSTRAINTS;

-- Transactions
DROP TABLE RESERVATIONS CASCADE CONSTRAINTS;
DROP TABLE LEDGER CASCADE CONSTRAINTS;
DROP TABLE STATISTICS CASCADE CONSTRAINTS;

-- Storage
DROP TABLE COPIES CASCADE CONSTRAINTS;
DROP TABLE COMPARTMENTS CASCADE CONSTRAINTS;
DROP TABLE SHELVES CASCADE CONSTRAINTS;
DROP TABLE LOCATIONS CASCADE CONSTRAINTS;

-- Subtypes
DROP TABLE AUDIOS CASCADE CONSTRAINTS;
DROP TABLE BOOKS CASCADE CONSTRAINTS;
DROP TABLE MOVIES CASCADE CONSTRAINTS;
DROP TABLE MAGAZINES CASCADE CONSTRAINTS;

-- Core
DROP TABLE MEDIAS CASCADE CONSTRAINTS;
DROP TABLE MEDIA_TYPES CASCADE CONSTRAINTS;
DROP TABLE GENRES CASCADE CONSTRAINTS;
DROP TABLE AUTHORS CASCADE CONSTRAINTS;
DROP TABLE CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE PRICES CASCADE CONSTRAINTS;

--create new Schema

-- 1. SEQUENCES
CREATE SEQUENCE media_seq START WITH 1;
CREATE SEQUENCE author_seq START WITH 1;
CREATE SEQUENCE customer_seq START WITH 1;
CREATE SEQUENCE genre_seq START WITH 1;
CREATE SEQUENCE location_seq START WITH 1;
CREATE SEQUENCE shelf_seq START WITH 1;
CREATE SEQUENCE compartment_seq START WITH 1;
CREATE SEQUENCE copy_seq START WITH 1;
CREATE SEQUENCE ledger_seq START WITH 1;
CREATE SEQUENCE reservation_seq START WITH 1;
CREATE SEQUENCE statistic_seq START WITH 1;


CREATE TABLE AUTHORS (
    author_id  INTEGER NOT NULL,
    last_name  VARCHAR2(50) NOT NULL,
    first_name VARCHAR2(50),
    CONSTRAINT AUTHORS_PK PRIMARY KEY (author_id)
);

CREATE TABLE CUSTOMERS (
    customer_id         INTEGER NOT NULL,
    customer_first_name VARCHAR2(50),
    customer_last_name  VARCHAR2(40) NOT NULL,
    birth_date          DATE NOT NULL,
    CONSTRAINT CUSTOMERS_PK PRIMARY KEY (customer_id)
);

CREATE TABLE GENRES (
    genre_id INTEGER NOT NULL,
    category VARCHAR2(30) NOT NULL,
    CONSTRAINT GENRES_PK PRIMARY KEY (genre_id)
);

CREATE TABLE MEDIA_TYPES (
    type_id INTEGER NOT NULL,
    type    VARCHAR2(30),
    CONSTRAINT MEDIA_TYPES_PK PRIMARY KEY (type_id)
);

CREATE TABLE LOCATIONS (
    loc_id INTEGER NOT NULL,
    name   VARCHAR2(30),
    street VARCHAR2(50),
    CONSTRAINT LOCATIONS_PK PRIMARY KEY (loc_id)
);

-- ==========================================================
-- 3. MEDIEN-HIERARCHIE
-- ==========================================================

CREATE TABLE MEDIAS (
    media_id            INTEGER NOT NULL,
    title               VARCHAR2(50) NOT NULL,
    description         VARCHAR2(200) NOT NULL,
    age_restriction     INTEGER NOT NULL,
    MEDIA_TYPES_type_id INTEGER NOT NULL,
    CONSTRAINT MEDIAS_PK PRIMARY KEY (media_id),
    CONSTRAINT MEDIAS_MEDIA_TYPES_FK FOREIGN KEY (MEDIA_TYPES_type_id) REFERENCES MEDIA_TYPES (type_id)
);

-- Untertypen von MEDIAS (1:1 Beziehungen)
CREATE TABLE AUDIOS (
    media_id INTEGER NOT NULL,
    codec    VARCHAR2(20) NOT NULL,
    duration DATE NOT NULL,
    CONSTRAINT AUDIOS_PK PRIMARY KEY (media_id),
    CONSTRAINT AUDIOS_MEDIAS_FK FOREIGN KEY (media_id) REFERENCES MEDIAS (media_id)
);

CREATE TABLE BOOKS (
    media_id INTEGER NOT NULL,
    isbn_id  VARCHAR2(50) NOT NULL,
    CONSTRAINT BOOKS_PK PRIMARY KEY (media_id),
    CONSTRAINT BOOKS_MEDIAS_FK FOREIGN KEY (media_id) REFERENCES MEDIAS (media_id)
);

CREATE TABLE MAGAZINES (
    media_id INTEGER NOT NULL,
    edition  VARCHAR2(30),
    CONSTRAINT MAGAZINES_PK PRIMARY KEY (media_id),
    CONSTRAINT MAGAZINES_MEDIAS_FK FOREIGN KEY (media_id) REFERENCES MEDIAS (media_id)
);

CREATE TABLE MOVIES (
    media_id INTEGER NOT NULL,
    format   VARCHAR2(20) NOT NULL,
    duration DATE NOT NULL,
    CONSTRAINT MOVIES_PK PRIMARY KEY (media_id),
    CONSTRAINT MOVIES_MEDIAS_FK FOREIGN KEY (media_id) REFERENCES MEDIAS (media_id)
);

-- Ortsbeziehungen

CREATE TABLE SHELVES (
    shelf_id         VARCHAR2(10) NOT NULL,
    LOCATIONS_loc_id INTEGER NOT NULL,
    shelf_code       VARCHAR2(20),
    CONSTRAINT SHELVES_PK PRIMARY KEY (shelf_id, LOCATIONS_loc_id),
    CONSTRAINT SHELVES_LOCATIONS_FK FOREIGN KEY (LOCATIONS_loc_id) REFERENCES LOCATIONS (loc_id)
);

CREATE TABLE COMPARTMENTS (
    comp_id                  INTEGER NOT NULL,
    SHELVES_shelf_id         VARCHAR2(10) NOT NULL,
    SHELVES_LOCATIONS_loc_id INTEGER NOT NULL,
    position                 VARCHAR2(20),
    CONSTRAINT COMPARTMENTS_PK PRIMARY KEY (comp_id, SHELVES_shelf_id, SHELVES_LOCATIONS_loc_id),
    CONSTRAINT COMPARTMENTS_SHELVES_FK FOREIGN KEY (SHELVES_shelf_id, SHELVES_LOCATIONS_loc_id) 
        REFERENCES SHELVES (shelf_id, LOCATIONS_loc_id)
);

CREATE TABLE COPIES (
    barcode_id            VARCHAR2(15) NOT NULL,
    MEDIAS_media_id       INTEGER NOT NULL,
    COMPARTMENTS_comp_id  INTEGER NOT NULL,
    COMPARTMENTS_shelf_id VARCHAR2(10) NOT NULL,
    COMPARTMENTS_loc_id   INTEGER NOT NULL,
    CONSTRAINT COPIES_PK PRIMARY KEY (barcode_id, MEDIAS_media_id),
    CONSTRAINT COPIES_MEDIAS_FK FOREIGN KEY (MEDIAS_media_id) REFERENCES MEDIAS (media_id),
    CONSTRAINT COPIES_COMPARTMENTS_FK FOREIGN KEY (COMPARTMENTS_comp_id, COMPARTMENTS_shelf_id, COMPARTMENTS_loc_id) 
        REFERENCES COMPARTMENTS (comp_id, SHELVES_shelf_id, SHELVES_LOCATIONS_loc_id)
);

-- 5. VERLEIH & TRANSAKTIONEN

CREATE TABLE LEDGER (
    start_date            DATE NOT NULL,
    end_date              DATE NOT NULL,
    return_dtime          DATE,
    total_cost            NUMBER(9,2),
    cost_paid             NUMBER(9,2),
    CUSTOMERS_customer_id INTEGER NOT NULL,
    COPIES_barcode_id     VARCHAR2(15) NOT NULL,
    COPIES_media_id       INTEGER NOT NULL,
    CONSTRAINT LEDGER_PK PRIMARY KEY (CUSTOMERS_customer_id, COPIES_barcode_id, COPIES_media_id, start_date),
    CONSTRAINT LEDGER_CUSTOMERS_FK FOREIGN KEY (CUSTOMERS_customer_id) REFERENCES CUSTOMERS (customer_id),
    CONSTRAINT LEDGER_COPIES_FK FOREIGN KEY (COPIES_barcode_id, COPIES_media_id) 
        REFERENCES COPIES (barcode_id, MEDIAS_media_id)
);

CREATE TABLE RESERVATIONS (
    reservation_id               INTEGER NOT NULL,
    time_reservation             DATE NOT NULL,
    CUSTOMERS_customer_id        INTEGER NOT NULL,
    MEDIAS_media_id              INTEGER NOT NULL,
    status                       VARCHAR2(20),
    LEDGER_CUSTOMERS_customer_id INTEGER NOT NULL,
    LEDGER_COPIES_barcode_id     VARCHAR2(15) NOT NULL,
    LEDGER_COPIES_media_id       INTEGER NOT NULL,
    LEDGER_start_date            DATE NOT NULL,
    CONSTRAINT RESERVATIONS_PK PRIMARY KEY (reservation_id, MEDIAS_media_id, CUSTOMERS_customer_id),
    CONSTRAINT RESERVATIONS_CUSTOMERS_FK FOREIGN KEY (CUSTOMERS_customer_id) REFERENCES CUSTOMERS (customer_id),
    CONSTRAINT RESERVATIONS_MEDIAS_FK FOREIGN KEY (MEDIAS_media_id) REFERENCES MEDIAS (media_id),
    CONSTRAINT RESERVATIONS_LEDGER_FK FOREIGN KEY (LEDGER_CUSTOMERS_customer_id, LEDGER_COPIES_barcode_id, LEDGER_COPIES_media_id, LEDGER_start_date)
        REFERENCES LEDGER (CUSTOMERS_customer_id, COPIES_barcode_id, COPIES_media_id, start_date)
);

-- 6. VERKNÜPFUNGEN & PREISE (N:M Beziehungen)

CREATE TABLE written_by (
    BOOKS_media_id    INTEGER NOT NULL,
    AUTHORS_author_id INTEGER NOT NULL,
    CONSTRAINT written_by_PK PRIMARY KEY (BOOKS_media_id, AUTHORS_author_id),
    CONSTRAINT written_by_BOOKS_FK FOREIGN KEY (BOOKS_media_id) REFERENCES BOOKS (media_id),
    CONSTRAINT written_by_AUTHORS_FK FOREIGN KEY (AUTHORS_author_id) REFERENCES AUTHORS (author_id)
);

CREATE TABLE MEDIA_GENRE (
    GENRES_genre_id INTEGER NOT NULL,
    MEDIAS_media_id INTEGER NOT NULL,
    CONSTRAINT MEDIA_GENRE_PK PRIMARY KEY (GENRES_genre_id, MEDIAS_media_id),
    CONSTRAINT MEDIA_GENRE_GENRES_FK FOREIGN KEY (GENRES_genre_id) REFERENCES GENRES (genre_id),
    CONSTRAINT MEDIA_GENRE_MEDIAS_FK FOREIGN KEY (MEDIAS_media_id) REFERENCES MEDIAS (media_id)
);

CREATE TABLE PRICES (
    MEDIA_TYPES_type_id INTEGER NOT NULL,
    GENRES_genre_id     INTEGER NOT NULL,
    creation_date       DATE NOT NULL,
    cost                NUMBER(9,2),
    valid               CHAR(1),
    CONSTRAINT PRICES_PK PRIMARY KEY (MEDIA_TYPES_type_id, GENRES_genre_id, creation_date),
    CONSTRAINT PRICES_GENRES_FK FOREIGN KEY (GENRES_genre_id) REFERENCES GENRES (genre_id),
    CONSTRAINT PRICES_MEDIA_TYPES_FK FOREIGN KEY (MEDIA_TYPES_type_id) REFERENCES MEDIA_TYPES (type_id)
);

CREATE TABLE STATISTICS (
    statistic_id           INTEGER NOT NULL,
    number_time_borrowed   INTEGER,
    sum_time_borrowed      INTEGER,
    COPIES_barcode_id      VARCHAR2(15) NOT NULL,
    COPIES_MEDIAS_media_id INTEGER NOT NULL,
    CONSTRAINT STATISTICS_PK PRIMARY KEY (statistic_id, COPIES_barcode_id, COPIES_MEDIAS_media_id),
    CONSTRAINT STATISTICS_COPIES_FK FOREIGN KEY (COPIES_barcode_id, COPIES_MEDIAS_media_id) 
        REFERENCES COPIES (barcode_id, MEDIAS_media_id)
);

-- 7. INDIZES & TRIGGER

CREATE UNIQUE INDEX RESERVATIONS__IDX ON RESERVATIONS (LEDGER_CUSTOMERS_customer_id, LEDGER_COPIES_barcode_id, LEDGER_COPIES_media_id, LEDGER_start_date);
CREATE UNIQUE INDEX STATISTICS__IDX ON STATISTICS (COPIES_barcode_id, COPIES_MEDIAS_media_id);

---- TRIGGER

-- 1. AUTHOR_SEQ -> AUTHORS
CREATE OR REPLACE TRIGGER TRG_AUTHORS_BI
BEFORE INSERT ON AUTHORS FOR EACH ROW
BEGIN
  IF :new.author_id IS NULL THEN
    SELECT AUTHOR_SEQ.NEXTVAL INTO :new.author_id FROM dual;
  END IF;
END;
/

-- 2. CUSTOMER_SEQ -> CUSTOMERS
CREATE OR REPLACE TRIGGER TRG_CUSTOMERS_BI
BEFORE INSERT ON CUSTOMERS FOR EACH ROW
BEGIN
  IF :new.customer_id IS NULL THEN
    SELECT CUSTOMER_SEQ.NEXTVAL INTO :new.customer_id FROM dual;
  END IF;
END;
/

-- 3. GENRE_SEQ -> GENRES
CREATE OR REPLACE TRIGGER TRG_GENRES_BI
BEFORE INSERT ON GENRES FOR EACH ROW
BEGIN
  IF :new.genre_id IS NULL THEN
    SELECT GENRE_SEQ.NEXTVAL INTO :new.genre_id FROM dual;
  END IF;
END;
/

-- 4. LOCATION_SEQ -> LOCATIONS
CREATE OR REPLACE TRIGGER TRG_LOCATIONS_BI
BEFORE INSERT ON LOCATIONS FOR EACH ROW
BEGIN
  IF :new.loc_id IS NULL THEN
    SELECT LOCATION_SEQ.NEXTVAL INTO :new.loc_id FROM dual;
  END IF;
END;
/

-- 5. MEDIA_SEQ -> MEDIAS (Parent table for Books, Movies, etc.)
CREATE OR REPLACE TRIGGER TRG_MEDIAS_BI
BEFORE INSERT ON MEDIAS FOR EACH ROW
BEGIN
  IF :new.media_id IS NULL THEN
    SELECT MEDIA_SEQ.NEXTVAL INTO :new.media_id FROM dual;
  END IF;
END;
/

-- 6. COMPARTMENT_SEQ -> COMPARTMENTS
-- Note: Only triggers the ID part of the composite key
CREATE OR REPLACE TRIGGER TRG_COMPARTMENTS_BI
BEFORE INSERT ON COMPARTMENTS FOR EACH ROW
BEGIN
  IF :new.comp_id IS NULL THEN
    SELECT COMPARTMENT_SEQ.NEXTVAL INTO :new.comp_id FROM dual;
  END IF;
END;
/

-- 7. RESERVATION_SEQ -> RESERVATIONS
CREATE OR REPLACE TRIGGER TRG_RESERVATIONS_BI
BEFORE INSERT ON RESERVATIONS FOR EACH ROW
BEGIN
  IF :new.reservation_id IS NULL THEN
    SELECT RESERVATION_SEQ.NEXTVAL INTO :new.reservation_id FROM dual;
  END IF;
END;
/

-- 8. STATISTIC_SEQ -> STATISTICS
CREATE OR REPLACE TRIGGER TRG_STATISTICS_BI
BEFORE INSERT ON STATISTICS FOR EACH ROW
BEGIN
  IF :new.statistic_id IS NULL THEN
    SELECT STATISTIC_SEQ.NEXTVAL INTO :new.statistic_id FROM dual;
  END IF;
END;
/

-- Hinweis: Die Trigger setzen voraus, dass die Variablen BOOKS, MOVIES etc. 
-- in deiner Applikation oder als Konstanten/IDs in der Tabelle MEDIA_TYPES definiert sind.
-- Hier ein Beispiel für BOOKS:
CREATE OR REPLACE TRIGGER ARC_FKArc_3_BOOKS 
BEFORE INSERT OR UPDATE OF media_id ON BOOKS 
FOR EACH ROW 
DECLARE 
    d INTEGER; 
BEGIN 
    SELECT A.MEDIA_TYPES_type_id INTO d FROM MEDIAS A WHERE A.media_id = :new.media_id; 
    -- Hier sollte '1' (oder die entsprechende ID für Books) stehen
    IF (d IS NULL) THEN 
        raise_application_error(-20223,'FK BOOKS_MEDIAS_FK violates Arc constraint.'); 
    END IF; 
EXCEPTION WHEN NO_DATA_FOUND THEN NULL; 
END; 
/

